name: CloudOps CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t cloudops-app .

      - name: Run container
        run: docker run -d -p 5000:5000 cloudops-app